name: Deploy
on:
  pull_request:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20']
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: yarn install
      - name: Build
        run: yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          enable_jekyll: false
          cname: caballe.ro
